services:
  address:
    - account: http://localhost:8081
    - dispatch: http://localhost:8082
    - order: http://localhost:8083
    - map: http://localhost:8084
    - message: http://localhost:8085
    - netty: http://localhost:8086
    - pay: http://localhost:8087
    - valuation: http://localhost:8088
    - file: http://localhost:8089
    - government: http://localhost:9999