mybatis:
  # 用于将配置路径下的 * .xml 文件加载到 mybatis 中
  mapper-locations: classpath:/mapper/*.xml
  # 指定POJO扫描包来让 mapper.xml 文件的 resultType 自动扫描到自定义POJO，这样就不用每次指定完全限定名
  # 没有指定前:mapper.xml: <select id="getUsers" resultType="com.mashibing.servicesms.entity.User">
  # 指定后:mapper.xml:  <select id="getUsers" resultType="User">
  type-aliases-package: com.mashibing.internalcommon.entity.serviceorder
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_taxi_three?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      #初始化提供的连接数
      initial-size: 5
      #数据库连接池的最小维持连接数
      min-idle: 5
      #最大的连接数
      max-total: 5
      #等待连接获取的最大超时时间
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
logging:
  level:
    com.mashibing.serviceorder.dao: debug
pagehelper:
  helper-dialect: mysql
  # 允许分页条件从参数中带入
  support-methods-arguments: true
  reasonable: true
  params: count=countSql
